---
# tasks file for webserver

- name: "Install Deps"
  yum: name={{item}} state=present
  with_items:
    - nodejs
    - java-1.8.0-openjdk
    - ruby
    - httpd

- name: "(Re)Start Apache"
  service: name=httpd state=restarted
    
